# Generated by Django 3.0 on 2023-08-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_Historico_localizacoes',
        ),
    ]
